import * as z from "zod";

export const komiteSchema = z.object({
  id: z.string().cuid().optional(), // Optional because it will be auto-generated by Prisma
  navn: z.string().min(1, "Navn is required"), // Ensure 'navn' is unique at the application logic level
  leder: z.string().optional(), // Optional 'leder'
  text1: z.string().optional(), // Optional 'text1'
  text2: z.string().optional(), // Optional 'text2'
  text3: z.string().optional(), // Optional 'text3'
  bilde: z.string().url(), // Ensure 'bilde' is a valid URL
  mail: z.string().email().optional(), // Optional and must be a valid email if provided
  mappe: z.string().optional(), // Required 'mappe'
  createdAt: z.date().optional(), // Optional because it will be auto-generated by Prisma
  updatedAt: z.date().optional(), // Optional because it will be auto-generated by Prisma
  arrangementer: z.array(z.object({})).optional(), // Placeholder for related Arrangement objects
  bookings: z.array(z.object({})).optional(), // Placeholder for related Booking objects
});

export type Komite = z.infer<typeof komiteSchema>;
